name: Weekend Cleanup
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * SAT'

jobs:
  fetchWebhooks:
    runs-on: ubuntu-latest
    outputs:
      hook_ids: ${{ steps.format.outputs.hook_ids }}

    steps:
      - uses: octokit/request-action@v2.x
        id: request
        with:
          route: GET /repos/${{ github.repository }}/hooks
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - id: format
        run: |
          echo "hook_ids=$(jq -n '${{ steps.request.outputs.data }}' | jq -rc '[.[] .id]')\n" >> $GITHUB_OUTPUT
      - run: |
          echo 'Deleting these webhook ids: ${{ steps.format.outputs.hook_ids }}'

  cleanWebhooks:
    runs-on: ubuntu-latest
    needs: [ fetchWebhooks ]
    if: fromJSON(needs.fetchWebhooks.outputs.hook_ids)[0] != null
    strategy:
      matrix:
        value: ${{fromJSON(needs.fetchWebhooks.outputs.hook_ids)}}
    steps:
      - uses: octokit/request-action@v2.x
        id: delete_webhook
        with:
          route: DELETE /repos/${{ github.repository }}/hooks/${{ matrix.value }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
